name = "hackthe6ix-2025"
compatibility_date = "2025-04-09"
main = "./.cloudflare/worker.js"

[site]
bucket = "./.next"

[build]
command = "npm run build"

[env.production]
name = "hackthe6ix-2025-prod"

[env.staging]
name = "hackthe6ix-2025-staging" 